language: python
notifications:
  email:
    on_success: never
    on_failure: change
python:
  - "2.6"
  - "2.7"
  # - "3.5"
os:
  - windows
  # - osx
  - linux
before_install:
  - pip install coverage
script: coverage run Tester.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
