language: python
notifications:
  email:
    on_success: never
    on_failure: change
python:
  - "2.6"
  - "2.7"
  # - "3.5"
os:
  - windows
  # - osx
  - linux
# https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-195620855
before_install:
  - pip install coverage
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
  #   brew install python; \
  #   # brew install python3; \
  #   # virtualenv venv -p python3; \
  #   source venv/bin/activate; \
script: python Tester.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
